### ISSUE TITLE
Multiple DataGrids

### ISSUE THREAD

**Issue by ONYXDave** [Inspirare-LLC/Radzen.Blazor.GridColumnVisibilityChooser#1]
When using with multiple grids on one URL it appears that the saving will get mixed up as the only identifier is the URL.  Also if using with a grid on a Dialog how will it store correctly.

**Comment by JonasPetraska** [comment]
Hi,

Thanks for the report, those are very good points.

I think the only way to make this functionality work is to add an additional identifier for the grid, such as ID. In this way all grids that want to use this functionality would have to have an ID assigned to them. This way different grids on the same page or even a popup would be differentiated.

What do you think?

**Comment by ONYXDave** [comment]
That is exactly what I was thinking adding an additional [Parameter] that is used as an ID in addition to the URL.

**Comment by JonasPetraska** [comment]
Implemented this feature, updated repository description and nuget. To use this, just apply an "id" attribute to a grid and everything else will be taken care of :)
