### ISSUE TITLE
How to manage columns visibility?

### ISSUE THREAD

**Issue by maciekkukuczka** [Inspirare-LLC/Radzen.Blazor.GridColumnVisibilityChooser#3]
Maybe this is a stupid question, but how do we manage the columns ...?
Where do we manage their visibility?
Any additional component? :)

**Comment by JonasPetraska** [comment]
Hi.

What exactly do you mean?

You use `RadzenGridColumnVisibilityChooser` to manage column visibility.
If `PreserveState` is not enabled, you use the method `GetDefaultVisibility` to manage initial visibility.

**Comment by maciekkukuczka** [comment]
Thanks for the quick answer.
I mean how to refer to a given column in the code and
is there any visual component for selecting columns from the GUI?

**Comment by JonasPetraska** [comment]
Currently there is no way to trigger column visibility from code, expect for the `GetDefaultVisibility` method. This method is used to set initial column visibility, on page load, if `PreserveState` is not enabled.

The main way to manage column visibility is to use razor visual component `RadzenGridColumnVisibilityChooser`. I have added a screenshot of how it look in the readme.

Are these the answers you were looking for?

**Comment by maciekkukuczka** [comment]
I understand that "RadzenGridColumnVisibilityChooser" is the component that is on the screenshot?
Unfortunately, it does not appear for me.

 What is "colName"?
I can't see property "Name" in RadzenDataGridColumn

If I paste Ypur example code:

`<RadzenGridColumnVisibilityChooser Grid = "@ grid" RefreshParentStateAction = "@ (() => InvokeAsync (StateHasChanged))" GetDefaultVisibility = "@ ((colName) => GetDefaultColumnVisibility (colName))" />
`
```
@code {
     bool GetDefaultColumnVisibility (string colName)
     {
         return colName == "Test1" || colName == "Test2"? false: true;
     }
}
```

causes an error

error CS1660: Cannot convert lambda expression to type 'bool' because it is not a delegate type

**Comment by JonasPetraska** [comment]
`colName` is either a `Property` or a `Title` of the `RadzenDataGridColumn`. If `Property` is present, it will pass `Property` if not `Title` will be used to indentify a column. 

Could you try replacing `RadzenGridColumnVisibilityChooser` with `Radzen.Blazor.GridColumnVisibilityChooser.RadzenGridColumnVisibilityChooser`?

**Comment by maciekkukuczka** [comment]
```
    <Radzen.Blazor.GridColumnVisibilityChooser.RadzenGridColumnVisibilityChooser Grid="@productGrid" RefreshParentStateAction="@(() => InvokeAsync(StateHasChanged))"
                                       GetDefaultVisibility="@((colName) => GetDefaultColumnVisibility(colName))"/>
```

                                       
                                       
                                     
```
  bool GetDefaultColumnVisibility(string colName)
    {
        return colName == "SKU" || colName == "Name" ? false : true;
    }  
```

("colName" is "Property" from `RadzenDataGridColumn`)


ok, now RadzenGridColumnVisibilityChooser shows up but empty.


![image](https://user-images.githubusercontent.com/32330973/137883523-f0041341-aeed-44df-aaf8-1bf6664b0fff.png)

**Comment by JonasPetraska** [comment]
Could you try calling `InvokeAsync(StateHasChanged);` in `OnAfterRender` as such: 
```
    protected override void OnAfterRender(bool firstRender)
    {
        InvokeAsync(StateHasChanged);
    }
```
? It might actually be required to do it in order for the picker to initialize.

**Comment by JonasPetraska** [comment]
Sorry, `colName` is actually `Title` of `RadzenDataGridColumn`.

**Comment by maciekkukuczka** [comment]
And now it works! :)
(calName is only Title, not Property)

Congratulations on a great plugin!
Maybe the choice of the column widths is missing for full happiness ;)

![image](https://user-images.githubusercontent.com/32330973/137886055-87aca792-da9d-45a7-be6b-7e8d97460edc.png)


But it's great anyway!
Thank You very much!

**Comment by JonasPetraska** [comment]
Happy to hear.
I appreciate the input from you.
I have updated the readme to clarify the usage in order to avoid the issues you have stumbled upon.

For column width, I don't think that it would be sexy. Besides, you can make the columns resizable by setting `AllowColumnResize="true"`. I would say including the column width and position in local storage (if enabled `PreserveState`) would be the next modification to look forward to :) That way when loading the page, you would not only have the column you left it with, but the order and width would be the same.

**Comment by maciekkukuczka** [comment]
And that is really the best idea! ;)
